[package]
name = "pgp"
version = "0.6.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
description = "OpenPGP implementation in Rust"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/rpgp/rpgp"
repository = "https://github.com/rpgp/rpgp"
readme = "README.md"

keywords = ["pgp", "gpg", "openpgp", "email", "encryption"]
categories = ["cryptography", "std", "email"]

exclude = ["tests/tests/*"]

edition = "2018"

[dependencies]
crc24 = "^0.1"
base64 = "^0.12.0"
byteorder = "^1.2"
chrono = "^0.4"
circular = "^0.3"
cipher = "^0.2.5"
sha-1 = "^0.9"
sha2 = "^0.9"
md-5 = "^0.9"
ripemd160 = "^0.9"
generic-array = "^0.14"
digest = "^0.9"
aes = "^0.6"
blowfish = "^0.7"
twofish = "^0.5"
des = "^0.6"
block-modes = "^0.7"
hex = "^0.4"
cfb-mode = "^0.6.0"
num-derive = "0.3.0"
num-traits = "0.2.6"
lazy_static = "1.2.0"
block-padding = "0.2.0"
log = "0.4.6"
try_from = "^0.3"
derive_builder = "0.9.0"
bitfield = "0.13.1"
sha3 = "0.9"
rand = "0.7"
smallvec = "1.6.1"
cast5 = "0.9.0"
rsa = "^0.3.0"
nom = "^4.2"
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }
clear_on_drop = { version = "0.2.3", features = ["no_cc"] }
thiserror = "1.0.9"
signature = "1.3.0"

[dependencies.x25519-dalek]
version = "0.6"
default-features = false
features = ["std", "u64_backend"]

[dependencies.ed25519-dalek]
version = "1.0.1"
default-features = false
features = ["std", "u64_backend"]

[dependencies.num-bigint]
version = "0.6"
features = ["rand", "i128", "u64_digit", "prime", "zeroize"]
package = "num-bigint-dig"

[dependencies.flate2]
version = "^1.0"
default-features = false
features = ["rust_backend"]

[dependencies.gperftools]
version = "0.2.0"
optional = true

[dependencies.buf_redux]
version = "0.8.1"
default-features = false

[dev-dependencies]
hex-literal = "^0.2"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
glob = "^0.3"
regex = "^1.1"
pretty_assertions = "0.6"
rand_xorshift = "0.2"
rand_chacha = "0.2"
pretty_env_logger = "0.3"

[features]
default = []
nightly = ["x25519-dalek/nightly", "ed25519-dalek/nightly", "rsa/nightly", "rand/nightly", "num-bigint/nightly", "clear_on_drop/nightly"]
profile = ["gperftools"]
asm = ["sha-1/asm", "sha2/asm", "md-5/asm", "nightly"]
wasm = ["chrono/wasmbind", "nightly", "rand/wasm-bindgen"]

[profile.bench]
debug = true

